/// Flutter icons Quran
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Quran
///      fonts:
///       - asset: fonts/Quran.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class Quran {
  Quran._();

  static const _kFontFam = 'Quran';
  static const String? _kFontPkg = null;

  static const IconData quran =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
